version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps10-{{ .Branch }}-{{ checksum "webapp/requirements.txt" }}
      - run:
          working_directory: ~/project/webapp
          command: |
            virtualenv venv/
            . venv/bin/activate
            pwd
            pip install -r requirements.txt
      - save_cache:
          key: deps10-{{ .Branch }}-{{ checksum "webapp/requirements.txt" }}
          paths:
            - "webapp/venv"
      - run:
          working_directory: ~/project/webapp
          command: |
            . venv/bin/activate
            pytest --junitxml=test-reports/junit.xml
      - store_test_results:
          path: webapp/test-reports
      - store_artifacts:
          path: webapp/test-reports